(include "../src/logos/javascript.mjs")
(include "../src/logos/node.mjs")
(include "../src/logos/metajs.mjs")

(def metajs (require "../lib/metajs_node")
    util (require 'util)
    inspect  util.inspect)

(set-in metajs '*assert-handler* metajs.test-handler)
(console.log (str "Testing " (metajs.version-string)))

(include "../src/runtime.mjs")

(include "./reader.mjs")
(include "./if.mjs")
(include "./while.mjs")
(include "./macros.mjs")
(include "./function.mjs")
(include "./object.mjs")
(include "./scope.mjs")
(include "./logos.mjs")
(include "./def.mjs")
(include "./get.mjs")
(include "./set.mjs")
(include "./let.mjs")
(include "./raw.mjs")
(include "./try.mjs")
(include "./chaining.mjs")
(include "./assert.mjs")
(include "./checking.mjs")
(include "./list.mjs")
(include "./quote.mjs")
(include "./switch.mjs")
(include "./hook.mjs")
(include "./yield.mjs")
(include "./format.mjs")
(include "./compiler.mjs")

(include "./last.mjs")

(metajs.print-testing-state)

